#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("StepCounter.Resource", IsApplication=true)]

namespace StepCounter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int cadence_names = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cadence_names_km = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cadence_values = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int history_spinner = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int ab_white = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int blue_background = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int red_background = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int paddingBottom = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int standard_padding = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_social_share = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_highscore = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_notification = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_unsupporteddevice = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_warning = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int wear_background = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0013
			public const int RelativeLayout1 = 2131427347;
			
			// aapt resource value: 0x7f0b0010
			public const int calories = 2131427344;
			
			// aapt resource value: 0x7f0b0002
			public const int completed = 2131427330;
			
			// aapt resource value: 0x7f0b000c
			public const int counter_layout = 2131427340;
			
			// aapt resource value: 0x7f0b0004
			public const int day = 2131427332;
			
			// aapt resource value: 0x7f0b0012
			public const int distance = 2131427346;
			
			// aapt resource value: 0x7f0b0001
			public const int fragment_host = 2131427329;
			
			// aapt resource value: 0x7f0b0005
			public const int high_score = 2131427333;
			
			// aapt resource value: 0x7f0b0000
			public const int main_layout = 2131427328;
			
			// aapt resource value: 0x7f0b0016
			public const int menu_history = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int menu_settings = 2131427351;
			
			// aapt resource value: 0x7f0b0015
			public const int menu_share = 2131427349;
			
			// aapt resource value: 0x7f0b0009
			public const int no_sensor_box = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int no_sensor_image = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int no_step_sensor = 2131427339;
			
			// aapt resource value: 0x7f0b000f
			public const int percentage = 2131427343;
			
			// aapt resource value: 0x7f0b0007
			public const int progressView = 2131427335;
			
			// aapt resource value: 0x7f0b0003
			public const int remaining = 2131427331;
			
			// aapt resource value: 0x7f0b0014
			public const int step_count = 2131427348;
			
			// aapt resource value: 0x7f0b000e
			public const int stepcount = 2131427342;
			
			// aapt resource value: 0x7f0b0006
			public const int steps = 2131427334;
			
			// aapt resource value: 0x7f0b000d
			public const int today = 2131427341;
			
			// aapt resource value: 0x7f0b0008
			public const int top_layer = 2131427336;
			
			// aapt resource value: 0x7f0b0011
			public const int warning = 2131427345;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int history = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item_history = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int simple_spinner_item_1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int simple_spinner_item_2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int step_entry = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int history = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int main = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int about = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int about_title = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f08003a
			public const int awesome = 2131230778;
			
			// aapt resource value: 0x7f080038
			public const int awesome_title = 2131230776;
			
			// aapt resource value: 0x7f080022
			public const int cadence = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int cadence0 = 2131230755;
			
			// aapt resource value: 0x7f08002a
			public const int cadence0_km = 2131230762;
			
			// aapt resource value: 0x7f080024
			public const int cadence1 = 2131230756;
			
			// aapt resource value: 0x7f08002b
			public const int cadence1_km = 2131230763;
			
			// aapt resource value: 0x7f080025
			public const int cadence2 = 2131230757;
			
			// aapt resource value: 0x7f08002c
			public const int cadence2_km = 2131230764;
			
			// aapt resource value: 0x7f080026
			public const int cadence3 = 2131230758;
			
			// aapt resource value: 0x7f08002d
			public const int cadence3_km = 2131230765;
			
			// aapt resource value: 0x7f080027
			public const int cadence4 = 2131230759;
			
			// aapt resource value: 0x7f08002e
			public const int cadence4_km = 2131230766;
			
			// aapt resource value: 0x7f080028
			public const int cadence5 = 2131230760;
			
			// aapt resource value: 0x7f08002f
			public const int cadence5_km = 2131230767;
			
			// aapt resource value: 0x7f080029
			public const int cadence6 = 2131230761;
			
			// aapt resource value: 0x7f080030
			public const int cadence6_km = 2131230768;
			
			// aapt resource value: 0x7f08000f
			public const int calories = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int calories_short = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int category_general_preferences = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int category_notifications_preferences = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int completed = 2131230734;
			
			// aapt resource value: 0x7f08001d
			public const int copyright = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int created_by = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int created_by_summary = 2131230746;
			
			// aapt resource value: 0x7f08001f
			public const int created_with = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int created_with_summary = 2131230752;
			
			// aapt resource value: 0x7f080041
			public const int custom_step_goal = 2131230785;
			
			// aapt resource value: 0x7f080017
			public const int enhanced = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int enhanced_summary = 2131230744;
			
			// aapt resource value: 0x7f080035
			public const int goal_double = 2131230773;
			
			// aapt resource value: 0x7f080034
			public const int goal_full = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int goal_half = 2131230771;
			
			// aapt resource value: 0x7f080036
			public const int goal_update = 2131230774;
			
			// aapt resource value: 0x7f080048
			public const int has_been_reset = 2131230792;
			
			// aapt resource value: 0x7f080039
			public const int high_score = 2131230777;
			
			// aapt resource value: 0x7f080037
			public const int high_score_title = 2131230775;
			
			// aapt resource value: 0x7f08001b
			public const int inspired_by = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int inspired_by_summary = 2131230748;
			
			// aapt resource value: 0x7f080012
			public const int kilometeres = 2131230738;
			
			// aapt resource value: 0x7f080032
			public const int menu_history = 2131230770;
			
			// aapt resource value: 0x7f080001
			public const int menu_settings = 2131230721;
			
			// aapt resource value: 0x7f08003c
			public const int menu_share = 2131230780;
			
			// aapt resource value: 0x7f080011
			public const int miles = 2131230737;
			
			// aapt resource value: 0x7f080044
			public const int month = 2131230788;
			
			// aapt resource value: 0x7f080031
			public const int no_history = 2131230769;
			
			// aapt resource value: 0x7f080042
			public const int no_step_sensor = 2131230786;
			
			// aapt resource value: 0x7f080008
			public const int notifications_accumulative = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int notifications_accumulative_summary = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int notifications_progress = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int notifications_progress_summary = 2131230727;
			
			// aapt resource value: 0x7f080021
			public const int ok = 2131230753;
			
			// aapt resource value: 0x7f08000d
			public const int percent_complete = 2131230733;
			
			// aapt resource value: 0x7f080047
			public const int reset_count = 2131230791;
			
			// aapt resource value: 0x7f080046
			public const int reset_high_score = 2131230790;
			
			// aapt resource value: 0x7f08003f
			public const int review_app = 2131230783;
			
			// aapt resource value: 0x7f080040
			public const int review_app_summary = 2131230784;
			
			// aapt resource value: 0x7f08003b
			public const int share_steps_on = 2131230779;
			
			// aapt resource value: 0x7f08003d
			public const int share_steps_today = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int share_steps_total = 2131230782;
			
			// aapt resource value: 0x7f08000a
			public const int steps = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int steps_cap = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int today = 2131230732;
			
			// aapt resource value: 0x7f080045
			public const int total = 2131230789;
			
			// aapt resource value: 0x7f08001e
			public const int version = 2131230750;
			
			// aapt resource value: 0x7f080043
			public const int week = 2131230787;
			
			// aapt resource value: 0x7f080013
			public const int weight_kg = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int weight_lbs = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int weight_title_kg = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int weight_title_lbs = 2131230742;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MyTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MyTheme_ActionBar = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int ThemeActionBar = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences_general = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
