#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyStepCounterAndroid.Resource", IsApplication=true)]

namespace MyStepCounterAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090007
			public const int calories = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int distance = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int menu_settings = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int no_step_sensor = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int percentage = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int progressView = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int stepcount = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int steps = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int today = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int top_layer = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int about = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int about_title = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int calories = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int category_general_preferences = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int completed = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int copyright = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int created_by = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int created_by_summary = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int created_with = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int created_with_summary = 2131099673;
			
			// aapt resource value: 0x7f060010
			public const int enhanced = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int enhanced_summary = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int inspired_by = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int inspired_by_summary = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int kilometeres = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int menu_settings = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int miles = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int no_step_sensor = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int ok = 2131099674;
			
			// aapt resource value: 0x7f060007
			public const int percent_complete = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int steps = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int today = 2131099654;
			
			// aapt resource value: 0x7f060017
			public const int version = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int weight_kg = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int weight_lbs = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int weight_title_kg = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int weight_title_lbs = 2131099663;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MyTheme_ActionBar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ThemeActionBar = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences_general = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
