#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyStepCounterAndroid.Resource", IsApplication=true)]

namespace MyStepCounterAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int standard_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_unsupporteddevice = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000a
			public const int calories = 2131361802;
			
			// aapt resource value: 0x7f0a0005
			public const int counter_layout = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public const int distance = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int menu_settings = 2131361804;
			
			// aapt resource value: 0x7f0a0002
			public const int no_sensor_box = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int no_sensor_image = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int no_step_sensor = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int percentage = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int progressView = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int stepcount = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int steps = 2131361800;
			
			// aapt resource value: 0x7f0a0006
			public const int today = 2131361798;
			
			// aapt resource value: 0x7f0a0001
			public const int top_layer = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int about = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int about_title = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int calories = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int category_general_preferences = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int completed = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int copyright = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int created_by = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int created_by_summary = 2131165203;
			
			// aapt resource value: 0x7f070018
			public const int created_with = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int created_with_summary = 2131165209;
			
			// aapt resource value: 0x7f070010
			public const int enhanced = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int enhanced_summary = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int inspired_by = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int inspired_by_summary = 2131165205;
			
			// aapt resource value: 0x7f07000b
			public const int kilometeres = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int menu_settings = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int miles = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int no_step_sensor = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int ok = 2131165210;
			
			// aapt resource value: 0x7f070007
			public const int percent_complete = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int steps = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int today = 2131165190;
			
			// aapt resource value: 0x7f070017
			public const int version = 2131165207;
			
			// aapt resource value: 0x7f07000c
			public const int weight_kg = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int weight_lbs = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int weight_title_kg = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int weight_title_lbs = 2131165199;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme_ActionBar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int ThemeActionBar = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences_general = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
